version: "3.9"
services:
    public-service:
        build: ./public-service
        ports:
            - "5000:443"
    subscription-service:
        build: ./subscription-service
        ports:
            - "5001:443"
        depends_on:
            - email-message-queue
    email-message-queue:
        image: rabbitmq:3.8
        container_name: 'rabbitmq'
        volumes:
            - ./email-message-queue:/rabbitmq
        ports:
            - "5672:5672"
            - "15672:15672"
    email-service:
        build: ./email-service
        ports:
            - "5002:444"
        depends_on:
            - email-message-queue