version: "3.9"
services:
    public-service:
        build: ./public-service
        ports:
            - "5000:8080"
    subscription-service:
        build: ./subscription-service
        depends_on:
            - email-message-queue
    email-message-queue:
        image: rabbitmq:3.8
        container_name: 'rabbitmq'
        volumes:
            - ./email-message-queue:/rabbitmq
        ports:
            - "5672"
    email-service:
        build: ./email-service
        depends_on:
            - email-message-queue