version: "3.9"
services:
    public-service:
        ports:
        - "5000:5000"
    subscription-service:
        ports:
        - "443:443"
    email-message-queue:
        image: rabbitmq:3.8
    email-service:
        ports:
        - "444:444"